In [3]:
# Import required libraries
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

print("UID: 22BAI71060")

# 1. Data Preparation
print("\n=== Data Preparation ===")

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Print initial data shapes
print("Initial shapes:")
print("Training data shape:", x_train.shape)
print("Training labels shape:", y_train.shape)
print("Testing data shape:", x_test.shape)
print("Testing labels shape:", y_test.shape)

# Normalize the images to range [0, 1]
x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255

# Flatten the images (reshape to 1D)
x_train = x_train.reshape((x_train.shape[0], 28 * 28))
x_test = x_test.reshape((x_test.shape[0], 28 * 28))

# One-hot encode the labels
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

print("\nAfter preprocessing:")
print("Training data shape:", x_train.shape)
print("Training labels shape:", y_train.shape)

# 2. Model Definition
print("\n=== Model Creation ===")

# Create the sequential model
model = Sequential([
    Dense(512, activation='relu', input_shape=(28 * 28,)),
    Dense(512, activation='relu'),
    Dense(256, activation='relu'),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

# Display model summary
model.summary()

# 3. Model Compilation
print("\n=== Model Compilation ===")
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 4. Model Training
print("\n=== Model Training ===")
history = model.fit(x_train, y_train,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.2,
                    verbose=1)

# 5. Model Evaluation
print("\n=== Model Evaluation ===")
test_loss, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print(f'Test accuracy: {test_accuracy:.4f}')
print(f'Test loss: {test_loss:.4f}')

# 6. Making Predictions
print("\n=== Making Predictions ===")
predictions = model.predict(x_test)

# Print results for first 5 test images
print("\nPredictions for first 5 images:")
for i in range(5):
    print(f'Image {i+1}:')
    print(f'Predicted digit: {np.argmax(predictions[i])}')
    print(f'Actual digit: {np.argmax(y_test[i])}')
    print()

# Print training history
print("\n=== Training History ===")
print("Final training accuracy:", history.history['accuracy'][-1])
print("Final validation accuracy:", history.history['val_accuracy'][-1])

TensorFlow version: 2.17.0

=== Data Preparation ===
Initial shapes:
Training data shape: (60000, 28, 28)
Training labels shape: (60000,)
Testing data shape: (10000, 28, 28)
Testing labels shape: (10000,)

After preprocessing:
Training data shape: (60000, 784)
Training labels shape: (60000, 10)

=== Model Creation ===


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 512)            │       262,656 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 837,706 (3.20 MB)

 Trainable params: 837,706 (3.20 MB)

 Non-trainable params: 0 (0.00 B)


=== Model Compilation ===

=== Model Training ===
Epoch 1/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 9s 18ms/step - accuracy: 0.8398 - loss: 0.5263 - val_accuracy: 0.9612 - val_loss: 0.1314
Epoch 2/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 7s 18ms/step - accuracy: 0.9681 - loss: 0.1038 - val_accuracy: 0.9683 - val_loss: 0.1087
Epoch 3/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.9813 - loss: 0.0619 - val_accuracy: 0.9753 - val_loss: 0.0886
Epoch 4/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.9860 - loss: 0.0441 - val_accuracy: 0.9745 - val_loss: 0.0950
Epoch 5/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.9886 - loss: 0.0366 - val_accuracy: 0.9759 - val_loss: 0.0869
Epoch 6/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 17ms/step - accuracy: 0.9898 - loss: 0.0344 - val_accuracy: 0.9753 - val_loss: 0.0952
Epoch 7/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - accuracy: 0.9914 - loss: 0.0262 - val_accuracy: 0.9765 - val_loss: 0.0926
Epoch 8/10
375/375 ━━━━━━━━━━━━━━━━━━━━ 6s 17m

In [5]:


from sklearn.metrics import confusion_matrix  # Add this line

# Print confusion matrix
print("\n=== Confusion Matrix ===")
y_pred = np.argmax(predictions, axis=1)
y_true = np.argmax(y_test, axis=1)
conf_matrix = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Print normalized confusion matrix
print("\nNormalized Confusion Matrix:")
conf_matrix_norm = conf_matrix.astype('float') / conf_matrix.sum(axis=1)[:, np.newaxis]
print(np.round(conf_matrix_norm, 2))


=== Confusion Matrix ===
Confusion Matrix:
[[ 974    1    0    0    0    0    2    1    1    1]
 [   0 1122    3    0    0    1    5    1    3    0]
 [   4    0 1021    1    1    0    1    3    1    0]
 [   0    0    8  989    0    7    0    4    2    0]
 [   0    0    8    0  953    0    2    1    0   18]
 [   5    0    0    6    1  870    3    0    5    2]
 [   7    2    0    1    4    3  939    0    2    0]
 [   1    3   15    0    0    0    0 1008    0    1]
 [   5    1   12    2    3    1    0    6  943    1]
 [   1    3    0    4    8    2    0   16    2  973]]

Normalized Confusion Matrix:
[[0.99 0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.99 0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.99 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.01 0.98 0.   0.01 0.   0.   0.   0.  ]
 [0.   0.   0.01 0.   0.97 0.   0.   0.   0.   0.02]
 [0.01 0.   0.   0.01 0.   0.98 0.   0.   0.01 0.  ]
 [0.01 0.   0.   0.   0.   0.   0.98 0.   0.   0.  ]
 [0.   0.   0.01 0.   0.

In [6]:
# After your confusion matrix code, add:

def calculate_metrics(conf_matrix, class_idx):
    # For binary metrics, we treat the specified class as positive and all others as negative
    TP = conf_matrix[class_idx, class_idx]
    FP = np.sum(conf_matrix[:, class_idx]) - TP
    FN = np.sum(conf_matrix[class_idx, :]) - TP
    TN = np.sum(conf_matrix) - TP - FP - FN
    
    # Calculate precision, recall, and F1 score
    precision = TP / (TP + FP) if (TP + FP) != 0 else 0
    recall = TP / (TP + FN) if (TP + FN) != 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) != 0 else 0
    
    return {
        'TP': TP,
        'TN': TN,
        'FP': FP,
        'FN': FN,
        'Precision': precision,
        'Recall': recall,
        'F1': f1
    }

print("\n=== Detailed Metrics for Each Digit ===")
for digit in range(10):
    metrics = calculate_metrics(conf_matrix, digit)
    print(f"\nDigit {digit}:")
    print(f"True Positives (TP): {metrics['TP']}")
    print(f"True Negatives (TN): {metrics['TN']}")
    print(f"False Positives (FP): {metrics['FP']}")
    print(f"False Negatives (FN): {metrics['FN']}")
    print(f"Precision: {metrics['Precision']:.4f}")
    print(f"Recall: {metrics['Recall']:.4f}")
    print(f"F1 Score: {metrics['F1']:.4f}")


=== Detailed Metrics for Each Digit ===

Digit 0:
True Positives (TP): 974
True Negatives (TN): 8997
False Positives (FP): 23
False Negatives (FN): 6
Precision: 0.9769
Recall: 0.9939
F1 Score: 0.9853

Digit 1:
True Positives (TP): 1122
True Negatives (TN): 8855
False Positives (FP): 10
False Negatives (FN): 13
Precision: 0.9912
Recall: 0.9885
F1 Score: 0.9899

Digit 2:
True Positives (TP): 1021
True Negatives (TN): 8922
False Positives (FP): 46
False Negatives (FN): 11
Precision: 0.9569
Recall: 0.9893
F1 Score: 0.9728

Digit 3:
True Positives (TP): 989
True Negatives (TN): 8976
False Positives (FP): 14
False Negatives (FN): 21
Precision: 0.9860
Recall: 0.9792
F1 Score: 0.9826

Digit 4:
True Positives (TP): 953
True Negatives (TN): 9001
False Positives (FP): 17
False Negatives (FN): 29
Precision: 0.9825
Recall: 0.9705
F1 Score: 0.9764

Digit 5:
True Positives (TP): 870
True Negatives (TN): 9094
False Positives (FP): 14
False Negatives (FN): 22
Precision: 0.9842
Recall: 0.9753
F1 Score: