In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('exp4_1.csv')
df

House_Area   Price
0        2600  550000
1        1500  350000
2        3000  565000
3        2250  480000
4        3200  610000
5        3600  680000
6        3200  650000
7        4000  725000
8        2800  580000
9        3800  705000

In [5]:
df.describe()

House_Area          Price
count    10.000000      10.000000
mean   2995.000000  589500.000000
std     752.200476  113319.852139
min    1500.000000  350000.000000
25%    2650.000000  553750.000000
50%    3100.000000  595000.000000
75%    3500.000000  672500.000000
max    4000.000000  725000.000000

In [6]:
lr=LinearRegression()
lr.fit(df[['House_Area']],df['Price'])

LinearRegression()

In [7]:
price = lr.predict([[2500]])

C:\Users\sanch\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [9]:
price

array([515868.47660661])

In [11]:
Y_pred = lr.predict(df[['House_Area']])
Y_pred

array([530743.5318376 , 367117.92429673, 590243.75276155, 478680.83852914,
       619993.86322353, 679494.08414748, 619993.86322353, 738994.30507143,
       560493.64229957, 709244.19460946])

In [13]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
print(np.sqrt(mean_squared_error(df['Price'], Y_pred)))
print(mean_absolute_error(df['Price'], Y_pred))

17022.55970490815
14118.80799253767


In [15]:
df1 = pd.read_csv('exp4_2.csv')
df1

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [16]:
x = df1.drop('Outcome',axis=1)
y = df1['Outcome']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=101)
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\sanch\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
predictions = logmodel.predict(x_test)
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.82      0.89      0.85       150
           1       0.75      0.63      0.68        81

    accuracy                           0.80       231
   macro avg       0.78      0.76      0.77       231
weighted avg       0.79      0.80      0.79       231



In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,predictions)

array([[133,  17],
       [ 30,  51]], dtype=int64)